/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const UsageGoals = IDL.Record({
  'monthlyWaterFlow' : IDL.Float64,
  'monthlyElectricityUsage' : IDL.Float64,
});
export const DailyLog = IDL.Record({
  'date' : IDL.Text,
  'waterUsed' : IDL.Float64,
  'electricityUsed' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateDailyLog' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGoals' : IDL.Func([], [UsageGoals], ['query']),
  'getLogsForMonth' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(DailyLog)],
      ['query'],
    ),
  'getTodayLog' : IDL.Func([], [IDL.Opt(DailyLog)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setGoals' : IDL.Func([UsageGoals], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const UsageGoals = IDL.Record({
    'monthlyWaterFlow' : IDL.Float64,
    'monthlyElectricityUsage' : IDL.Float64,
  });
  const DailyLog = IDL.Record({
    'date' : IDL.Text,
    'waterUsed' : IDL.Float64,
    'electricityUsed' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateDailyLog' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGoals' : IDL.Func([], [UsageGoals], ['query']),
    'getLogsForMonth' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(DailyLog)],
        ['query'],
      ),
    'getTodayLog' : IDL.Func([], [IDL.Opt(DailyLog)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setGoals' : IDL.Func([UsageGoals], [], []),
  });
};

export const init = ({ IDL }) => { return []; };